### PR TITLE
Projet

### PR DESCRIPTION
**Pull request by muhammedInan**
confirm uml diagrams

### CODE REVIEW

**Comment by eddymio** [comment]
A few notes 
- context diag is fine (english version ?)
- package diag is fine but please translate in english and avoid crossing arrows (you may use generalization) 
- use cases diagrams don't match the packages you defined ! 
  > contact should belong to frontend package...
  > replace include with extend from blog page to contact form page
  > do you actually store the email being sent to the DB (need bdd ?)...

  > do you have an authentication package ?
  > data validation should be linked to form sending and not form registration

- frontend package use cases : no DB  to list articles and comments ?

I don't see the package named Gestion Compte ?

Sequences : 
- Sign in -> not bad - may be clarify the opt with [indication] you could also add the sigin in sequence and not just the registration - in english
- Admin -> missing the add article request, you go from articles listing to db update !  Modification and Delete are fine

- Blog  -> missing db request to list articles and retrieve one article and its comments.

Class diagram : 
Write Entities with capital letter for first one. No S at the end - we are talking about one Entity at a time.
1 entity = 1 id ...
ID are at the top of the attributes.

What is the difference between author and users_id (are you sure it is userS_id ? - 1 user)

Any role for users ? - just a question :)

**Review by muhammedInan — COMMENTED** [review]
last update

**Review by muhammedInan — COMMENTED** [review]
last update

**Comment by muhammedInan** [comment]
confirm structur model view controller

**Comment by muhammedInan** [comment]
update diagrams for confirm

**Comment by eddymio** [comment]
Much better now :+1: 
You can merge, but please do update the following : 
- try not crossing arrows in the package diag
- front end use case 
   - link  the Consult post with an actor !
   - comment a post is linked to consult a post and not post list
   - db is used for consult comment and consult a post
- admin use case diag
   - why notifications is linked to admin page ?
- authentication use case diag
   - remove the send form
   - could the ext annotation be more clear within the sign in use case ?
- sequence diag for registraion
  - remove the ref !

- class diag
   - Where is Role entity ? -> may be just type String as type for the role field
   - DO REVIEW your relationships !  1 media for 0 ou more post ???  0 or more posts with only 1 comment !!  0 or more users have 0 or more comments each (same comment for several users)!
  - Please Capital letter for name of Classes

**Comment by muhammedInan** [comment]
i take a note

**Pull request merged**
